spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bff
    username: postgres
    password: 123456
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
logstash:
  host: localhost
  port: 12201
  level: INFO
  level_local: INFO

api:
  ordering:
    basePath: ${ORDERING_BASE_PATH:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: localhost
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: 8091
  health:
    livenessState:
      enable: true
    readinessState:
      enable: true